#!/usr/bin/env ruby

require 'octokit'
require 'gemoji'

raise 'MY_GITHUB_TOKEN not defined.' unless ENV['MY_GITHUB_TOKEN']
unless ARGV.size == 2
  STDERR.puts "usage: review-requested-prs organization repository"
  raise 'argument error'
end

organization = ARGV.shift
repository   = ARGV.shift

client = Octokit::Client.new(access_token: ENV['MY_GITHUB_TOKEN'])

prs = client.search_issues("repo:#{organization}/#{repository} is:pr is:open review-requested:#{client.user.login}", per_page: 100)
prs.items.each do |pr_item|
  labels = pr_item.labels.map do |label|
    emojified_label = label.name.gsub(/:(?<emoji>.+?):(?<body>.*)$/) do
      emoji = Emoji.find_by_alias($1)
      emoji ? "#{emoji.raw} #{$2}" : "[#{$2}]"
    end
    "[#{emojified_label}]"
  end
  puts "##{pr_item.number} #{pr_item.title} #{labels.join}"
  puts "    #{pr_item.html_url}"
end
